# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: 'Lucene.Net.Website'

# The tag will be in the format: Website_4_8_0_beta00013 which will be parsed to create the version number
# used in the docs like 4.8.0-beta00013

# This will:
# checkout this repo
# Build the website
# Checkout the website repo
# Create a branch
# Commit/Push to the branch
# Create a PR, see https://github.com/peter-evans/create-pull-request ... might work?

on:
  create:
    tags:
      - Website_*

jobs:
  build-website:
    runs-on: windows-latest
    steps:
      - name: Set version from tag
        run: |
          $ref = "refs/tags/Website_4_8_0_Beta00013"
          echo "current_tag=$tag" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # set the release_version now to something incase parsing fails
          echo "release_version=UNKNOWN" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          $tag = $ref.Substring(10)
          $parts = $tag.Split("_")
          $version = "";
          For ($i=0; $i -le $parts.Length; $i++) {
              $version += $parts[$i]
              if ($i -eq ($parts.Length - 2)) {
                  $version += "-"
              }
              elseif ($i -lt ($parts.Length - 1)) {
                  $version += "."
              }
          }
          echo "release_version=$version" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell
      - name: Checkout Lucene.Net source
        uses: actions/checkout@v2
        with:
          path: main-repo
      - name: Build website
        run: ./main-repo/websites/site/site.ps1
        shell: powershell
      - name: Checkout Lucene.Net website
        uses: actions/checkout@v2
        with:
          repository: apache/lucenenet-site
          ref: asf-site
          path: website-repo
      - name: Copy website files
        run: Get-ChildItem -Path "$Env:GITHUB_WORKSPACE\main-repo\websites\site\_site" | Copy-Item -Destination "$Env:GITHUB_WORKSPACE\website-repo" -Recurse -Force
        shell: powershell
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          path: website-repo
          commit-message: New website version built
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ env.current_tag }}
          delete-branch: true
          title: 'New website version built ${{ env.current_tag }}'
          body: |
            New website version built ${{ env.current_tag }}
            - For version ${{ env.release_version }}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
